package entities;
// Generated Apr 15, 2016 4:34:07 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Bangluong generated by hbm2java
 */
public class Bangluong  implements java.io.Serializable {


     private Integer maLuong;
     private Nhanvien nhanvien;
     private Date ngayGioNhan;
     private int tongCaLam;
     private Integer vangCoPhep;
     private Integer vangKhongPhep;
     private Integer thoiGianTre;
     private int tongLuong;

    public Bangluong() {
    }

	
    public Bangluong(Nhanvien nhanvien, Date ngayGioNhan, int tongCaLam, int tongLuong) {
        this.nhanvien = nhanvien;
        this.ngayGioNhan = ngayGioNhan;
        this.tongCaLam = tongCaLam;
        this.tongLuong = tongLuong;
    }
    public Bangluong(Nhanvien nhanvien, Date ngayGioNhan, int tongCaLam, Integer vangCoPhep, Integer vangKhongPhep, Integer thoiGianTre, int tongLuong) {
       this.nhanvien = nhanvien;
       this.ngayGioNhan = ngayGioNhan;
       this.tongCaLam = tongCaLam;
       this.vangCoPhep = vangCoPhep;
       this.vangKhongPhep = vangKhongPhep;
       this.thoiGianTre = thoiGianTre;
       this.tongLuong = tongLuong;
    }
   
    public Integer getMaLuong() {
        return this.maLuong;
    }
    
    public void setMaLuong(Integer maLuong) {
        this.maLuong = maLuong;
    }
    public Nhanvien getNhanvien() {
        return this.nhanvien;
    }
    
    public void setNhanvien(Nhanvien nhanvien) {
        this.nhanvien = nhanvien;
    }
    public Date getNgayGioNhan() {
        return this.ngayGioNhan;
    }
    
    public void setNgayGioNhan(Date ngayGioNhan) {
        this.ngayGioNhan = ngayGioNhan;
    }
    public int getTongCaLam() {
        return this.tongCaLam;
    }
    
    public void setTongCaLam(int tongCaLam) {
        this.tongCaLam = tongCaLam;
    }
    public Integer getVangCoPhep() {
        return this.vangCoPhep;
    }
    
    public void setVangCoPhep(Integer vangCoPhep) {
        this.vangCoPhep = vangCoPhep;
    }
    public Integer getVangKhongPhep() {
        return this.vangKhongPhep;
    }
    
    public void setVangKhongPhep(Integer vangKhongPhep) {
        this.vangKhongPhep = vangKhongPhep;
    }
    public Integer getThoiGianTre() {
        return this.thoiGianTre;
    }
    
    public void setThoiGianTre(Integer thoiGianTre) {
        this.thoiGianTre = thoiGianTre;
    }
    public int getTongLuong() {
        return this.tongLuong;
    }
    
    public void setTongLuong(int tongLuong) {
        this.tongLuong = tongLuong;
    }




}


