package entities;
// Generated Apr 15, 2016 4:34:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Banghe generated by hbm2java
 */
public class Banghe  implements java.io.Serializable {


     private String maBan;
     private Nhanvien nhanvien;
     private Trangthai trangthai;
     private int soLuongKhach;
     private int soKhachToiDa;
     private boolean xoa;
     private Set chitietgoimenus = new HashSet(0);
     private Set hoadons = new HashSet(0);

    public Banghe() {
    }

	
    public Banghe(String maBan, int soLuongKhach, int soKhachToiDa, boolean xoa) {
        this.maBan = maBan;
        this.soLuongKhach = soLuongKhach;
        this.soKhachToiDa = soKhachToiDa;
        this.xoa = xoa;
    }
    public Banghe(String maBan, Nhanvien nhanvien, Trangthai trangthai, int soLuongKhach, int soKhachToiDa, boolean xoa, Set chitietgoimenus, Set hoadons) {
       this.maBan = maBan;
       this.nhanvien = nhanvien;
       this.trangthai = trangthai;
       this.soLuongKhach = soLuongKhach;
       this.soKhachToiDa = soKhachToiDa;
       this.xoa = xoa;
       this.chitietgoimenus = chitietgoimenus;
       this.hoadons = hoadons;
    }
   
    public String getMaBan() {
        return this.maBan;
    }
    
    public void setMaBan(String maBan) {
        this.maBan = maBan;
    }
    public Nhanvien getNhanvien() {
        return this.nhanvien;
    }
    
    public void setNhanvien(Nhanvien nhanvien) {
        this.nhanvien = nhanvien;
    }
    public Trangthai getTrangthai() {
        return this.trangthai;
    }
    
    public void setTrangthai(Trangthai trangthai) {
        this.trangthai = trangthai;
    }
    public int getSoLuongKhach() {
        return this.soLuongKhach;
    }
    
    public void setSoLuongKhach(int soLuongKhach) {
        this.soLuongKhach = soLuongKhach;
    }
    public int getSoKhachToiDa() {
        return this.soKhachToiDa;
    }
    
    public void setSoKhachToiDa(int soKhachToiDa) {
        this.soKhachToiDa = soKhachToiDa;
    }
    public boolean isXoa() {
        return this.xoa;
    }
    
    public void setXoa(boolean xoa) {
        this.xoa = xoa;
    }
    public Set getChitietgoimenus() {
        return this.chitietgoimenus;
    }
    
    public void setChitietgoimenus(Set chitietgoimenus) {
        this.chitietgoimenus = chitietgoimenus;
    }
    public Set getHoadons() {
        return this.hoadons;
    }
    
    public void setHoadons(Set hoadons) {
        this.hoadons = hoadons;
    }




}


