package entities;
// Generated Apr 15, 2016 4:34:07 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Chitietgoimenu generated by hbm2java
 */
public class Chitietgoimenu  implements java.io.Serializable {


     private Integer maCtg;
     private Banghe banghe;
     private Menu menu;
     private Trangthai trangthai;
     private String tenGoi;
     private int soLuongGoi;
     private String ghiChu;
     private Date thoiGianGoi;

    public Chitietgoimenu() {
    }

    public Chitietgoimenu(Banghe banghe, Menu menu, Trangthai trangthai, String tenGoi, int soLuongGoi, String ghiChu, Date thoiGianGoi) {
       this.banghe = banghe;
       this.menu = menu;
       this.trangthai = trangthai;
       this.tenGoi = tenGoi;
       this.soLuongGoi = soLuongGoi;
       this.ghiChu = ghiChu;
       this.thoiGianGoi = thoiGianGoi;
    }
   
    public Integer getMaCtg() {
        return this.maCtg;
    }
    
    public void setMaCtg(Integer maCtg) {
        this.maCtg = maCtg;
    }
    public Banghe getBanghe() {
        return this.banghe;
    }
    
    public void setBanghe(Banghe banghe) {
        this.banghe = banghe;
    }
    public Menu getMenu() {
        return this.menu;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
    }
    public Trangthai getTrangthai() {
        return this.trangthai;
    }
    
    public void setTrangthai(Trangthai trangthai) {
        this.trangthai = trangthai;
    }
    public String getTenGoi() {
        return this.tenGoi;
    }
    
    public void setTenGoi(String tenGoi) {
        this.tenGoi = tenGoi;
    }
    public int getSoLuongGoi() {
        return this.soLuongGoi;
    }
    
    public void setSoLuongGoi(int soLuongGoi) {
        this.soLuongGoi = soLuongGoi;
    }
    public String getGhiChu() {
        return this.ghiChu;
    }
    
    public void setGhiChu(String ghiChu) {
        this.ghiChu = ghiChu;
    }
    public Date getThoiGianGoi() {
        return this.thoiGianGoi;
    }
    
    public void setThoiGianGoi(Date thoiGianGoi) {
        this.thoiGianGoi = thoiGianGoi;
    }




}


