package entities;
// Generated Apr 15, 2016 4:34:07 PM by Hibernate Tools 4.3.1



/**
 * Chitiethoadon generated by hbm2java
 */
public class Chitiethoadon  implements java.io.Serializable {


     private Integer maCthd;
     private Hoadon hoadon;
     private Menu menu;
     private String tenGoi;
     private int donGia;
     private int soLuong;
     private int thanhTien;

    public Chitiethoadon() {
    }

    public Chitiethoadon(Hoadon hoadon, Menu menu, String tenGoi, int donGia, int soLuong, int thanhTien) {
       this.hoadon = hoadon;
       this.menu = menu;
       this.tenGoi = tenGoi;
       this.donGia = donGia;
       this.soLuong = soLuong;
       this.thanhTien = thanhTien;
    }
   
    public Integer getMaCthd() {
        return this.maCthd;
    }
    
    public void setMaCthd(Integer maCthd) {
        this.maCthd = maCthd;
    }
    public Hoadon getHoadon() {
        return this.hoadon;
    }
    
    public void setHoadon(Hoadon hoadon) {
        this.hoadon = hoadon;
    }
    public Menu getMenu() {
        return this.menu;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
    }
    public String getTenGoi() {
        return this.tenGoi;
    }
    
    public void setTenGoi(String tenGoi) {
        this.tenGoi = tenGoi;
    }
    public int getDonGia() {
        return this.donGia;
    }
    
    public void setDonGia(int donGia) {
        this.donGia = donGia;
    }
    public int getSoLuong() {
        return this.soLuong;
    }
    
    public void setSoLuong(int soLuong) {
        this.soLuong = soLuong;
    }
    public int getThanhTien() {
        return this.thanhTien;
    }
    
    public void setThanhTien(int thanhTien) {
        this.thanhTien = thanhTien;
    }




}


