package entities;
// Generated Apr 15, 2016 4:34:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Hoadon generated by hbm2java
 */
public class Hoadon  implements java.io.Serializable {


     private Integer maHd;
     private Banghe banghe;
     private Nhanvien nhanvien;
     private String tenKhachHang;
     private String tenNhanVien;
     private int soLuongKhach;
     private Date ngayGio;
     private int tongTien;
     private boolean thanhToan;
     private Set chitiethoadons = new HashSet(0);

    public Hoadon() {
    }

	
    public Hoadon(Banghe banghe, Nhanvien nhanvien, String tenKhachHang, int soLuongKhach, Date ngayGio, int tongTien, boolean thanhToan) {
        this.banghe = banghe;
        this.nhanvien = nhanvien;
        this.tenKhachHang = tenKhachHang;
        this.soLuongKhach = soLuongKhach;
        this.ngayGio = ngayGio;
        this.tongTien = tongTien;
        this.thanhToan = thanhToan;
    }
    public Hoadon(Banghe banghe, Nhanvien nhanvien, String tenKhachHang, String tenNhanVien, int soLuongKhach, Date ngayGio, int tongTien, boolean thanhToan, Set chitiethoadons) {
       this.banghe = banghe;
       this.nhanvien = nhanvien;
       this.tenKhachHang = tenKhachHang;
       this.tenNhanVien = tenNhanVien;
       this.soLuongKhach = soLuongKhach;
       this.ngayGio = ngayGio;
       this.tongTien = tongTien;
       this.thanhToan = thanhToan;
       this.chitiethoadons = chitiethoadons;
    }
   
    public Integer getMaHd() {
        return this.maHd;
    }
    
    public void setMaHd(Integer maHd) {
        this.maHd = maHd;
    }
    public Banghe getBanghe() {
        return this.banghe;
    }
    
    public void setBanghe(Banghe banghe) {
        this.banghe = banghe;
    }
    public Nhanvien getNhanvien() {
        return this.nhanvien;
    }
    
    public void setNhanvien(Nhanvien nhanvien) {
        this.nhanvien = nhanvien;
    }
    public String getTenKhachHang() {
        return this.tenKhachHang;
    }
    
    public void setTenKhachHang(String tenKhachHang) {
        this.tenKhachHang = tenKhachHang;
    }
    public String getTenNhanVien() {
        return this.tenNhanVien;
    }
    
    public void setTenNhanVien(String tenNhanVien) {
        this.tenNhanVien = tenNhanVien;
    }
    public int getSoLuongKhach() {
        return this.soLuongKhach;
    }
    
    public void setSoLuongKhach(int soLuongKhach) {
        this.soLuongKhach = soLuongKhach;
    }
    public Date getNgayGio() {
        return this.ngayGio;
    }
    
    public void setNgayGio(Date ngayGio) {
        this.ngayGio = ngayGio;
    }
    public int getTongTien() {
        return this.tongTien;
    }
    
    public void setTongTien(int tongTien) {
        this.tongTien = tongTien;
    }
    public boolean isThanhToan() {
        return this.thanhToan;
    }
    
    public void setThanhToan(boolean thanhToan) {
        this.thanhToan = thanhToan;
    }
    public Set getChitiethoadons() {
        return this.chitiethoadons;
    }
    
    public void setChitiethoadons(Set chitiethoadons) {
        this.chitiethoadons = chitiethoadons;
    }




}


