package entities;
// Generated Apr 15, 2016 4:34:07 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Lichcalamviec generated by hbm2java
 */
public class Lichcalamviec  implements java.io.Serializable {


     private Integer maLich;
     private Calamviec calamviec;
     private Nhanvien nhanvien;
     private Trangthai trangthai;
     private Date thoiGian;
     private Integer thoiGianTre;

    public Lichcalamviec() {
    }

	
    public Lichcalamviec(Calamviec calamviec, Nhanvien nhanvien, Date thoiGian) {
        this.calamviec = calamviec;
        this.nhanvien = nhanvien;
        this.thoiGian = thoiGian;
    }
    public Lichcalamviec(Calamviec calamviec, Nhanvien nhanvien, Trangthai trangthai, Date thoiGian, Integer thoiGianTre) {
       this.calamviec = calamviec;
       this.nhanvien = nhanvien;
       this.trangthai = trangthai;
       this.thoiGian = thoiGian;
       this.thoiGianTre = thoiGianTre;
    }
   
    public Integer getMaLich() {
        return this.maLich;
    }
    
    public void setMaLich(Integer maLich) {
        this.maLich = maLich;
    }
    public Calamviec getCalamviec() {
        return this.calamviec;
    }
    
    public void setCalamviec(Calamviec calamviec) {
        this.calamviec = calamviec;
    }
    public Nhanvien getNhanvien() {
        return this.nhanvien;
    }
    
    public void setNhanvien(Nhanvien nhanvien) {
        this.nhanvien = nhanvien;
    }
    public Trangthai getTrangthai() {
        return this.trangthai;
    }
    
    public void setTrangthai(Trangthai trangthai) {
        this.trangthai = trangthai;
    }
    public Date getThoiGian() {
        return this.thoiGian;
    }
    
    public void setThoiGian(Date thoiGian) {
        this.thoiGian = thoiGian;
    }
    public Integer getThoiGianTre() {
        return this.thoiGianTre;
    }
    
    public void setThoiGianTre(Integer thoiGianTre) {
        this.thoiGianTre = thoiGianTre;
    }




}


