package entities;
// Generated Apr 15, 2016 4:34:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Nhanvien generated by hbm2java
 */
public class Nhanvien  implements java.io.Serializable {


     private String maNhanVien;
     private Trinhdovitinh trinhdovitinh;
     private Vitrinhanvien vitrinhanvien;
     private String matKhau;
     private String cauHoiBaoMat;
     private String dapAnBaoMat;
     private String hoTen;
     private Date sinhNhat;
     private int sodt;
     private int cmnd;
     private Date ngayBatDau;
     private boolean trangPhuc;
     private int luongTheoCa;
     private boolean nghiViec;
     private Set hoadons = new HashSet(0);
     private Set bangluongs = new HashSet(0);
     private Set banghes = new HashSet(0);
     private Set lichcalamviecs = new HashSet(0);

    public Nhanvien() {
    }

	
    public Nhanvien(String maNhanVien, Trinhdovitinh trinhdovitinh, Vitrinhanvien vitrinhanvien, String matKhau, String cauHoiBaoMat, String dapAnBaoMat, String hoTen, int sodt, int cmnd, Date ngayBatDau, boolean trangPhuc, int luongTheoCa, boolean nghiViec) {
        this.maNhanVien = maNhanVien;
        this.trinhdovitinh = trinhdovitinh;
        this.vitrinhanvien = vitrinhanvien;
        this.matKhau = matKhau;
        this.cauHoiBaoMat = cauHoiBaoMat;
        this.dapAnBaoMat = dapAnBaoMat;
        this.hoTen = hoTen;
        this.sodt = sodt;
        this.cmnd = cmnd;
        this.ngayBatDau = ngayBatDau;
        this.trangPhuc = trangPhuc;
        this.luongTheoCa = luongTheoCa;
        this.nghiViec = nghiViec;
    }
    public Nhanvien(String maNhanVien, Trinhdovitinh trinhdovitinh, Vitrinhanvien vitrinhanvien, String matKhau, String cauHoiBaoMat, String dapAnBaoMat, String hoTen, Date sinhNhat, int sodt, int cmnd, Date ngayBatDau, boolean trangPhuc, int luongTheoCa, boolean nghiViec, Set hoadons, Set bangluongs, Set banghes, Set lichcalamviecs) {
       this.maNhanVien = maNhanVien;
       this.trinhdovitinh = trinhdovitinh;
       this.vitrinhanvien = vitrinhanvien;
       this.matKhau = matKhau;
       this.cauHoiBaoMat = cauHoiBaoMat;
       this.dapAnBaoMat = dapAnBaoMat;
       this.hoTen = hoTen;
       this.sinhNhat = sinhNhat;
       this.sodt = sodt;
       this.cmnd = cmnd;
       this.ngayBatDau = ngayBatDau;
       this.trangPhuc = trangPhuc;
       this.luongTheoCa = luongTheoCa;
       this.nghiViec = nghiViec;
       this.hoadons = hoadons;
       this.bangluongs = bangluongs;
       this.banghes = banghes;
       this.lichcalamviecs = lichcalamviecs;
    }
   
    public String getMaNhanVien() {
        return this.maNhanVien;
    }
    
    public void setMaNhanVien(String maNhanVien) {
        this.maNhanVien = maNhanVien;
    }
    public Trinhdovitinh getTrinhdovitinh() {
        return this.trinhdovitinh;
    }
    
    public void setTrinhdovitinh(Trinhdovitinh trinhdovitinh) {
        this.trinhdovitinh = trinhdovitinh;
    }
    public Vitrinhanvien getVitrinhanvien() {
        return this.vitrinhanvien;
    }
    
    public void setVitrinhanvien(Vitrinhanvien vitrinhanvien) {
        this.vitrinhanvien = vitrinhanvien;
    }
    public String getMatKhau() {
        return this.matKhau;
    }
    
    public void setMatKhau(String matKhau) {
        this.matKhau = matKhau;
    }
    public String getCauHoiBaoMat() {
        return this.cauHoiBaoMat;
    }
    
    public void setCauHoiBaoMat(String cauHoiBaoMat) {
        this.cauHoiBaoMat = cauHoiBaoMat;
    }
    public String getDapAnBaoMat() {
        return this.dapAnBaoMat;
    }
    
    public void setDapAnBaoMat(String dapAnBaoMat) {
        this.dapAnBaoMat = dapAnBaoMat;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public Date getSinhNhat() {
        return this.sinhNhat;
    }
    
    public void setSinhNhat(Date sinhNhat) {
        this.sinhNhat = sinhNhat;
    }
    public int getSodt() {
        return this.sodt;
    }
    
    public void setSodt(int sodt) {
        this.sodt = sodt;
    }
    public int getCmnd() {
        return this.cmnd;
    }
    
    public void setCmnd(int cmnd) {
        this.cmnd = cmnd;
    }
    public Date getNgayBatDau() {
        return this.ngayBatDau;
    }
    
    public void setNgayBatDau(Date ngayBatDau) {
        this.ngayBatDau = ngayBatDau;
    }
    public boolean isTrangPhuc() {
        return this.trangPhuc;
    }
    
    public void setTrangPhuc(boolean trangPhuc) {
        this.trangPhuc = trangPhuc;
    }
    public int getLuongTheoCa() {
        return this.luongTheoCa;
    }
    
    public void setLuongTheoCa(int luongTheoCa) {
        this.luongTheoCa = luongTheoCa;
    }
    public boolean isNghiViec() {
        return this.nghiViec;
    }
    
    public void setNghiViec(boolean nghiViec) {
        this.nghiViec = nghiViec;
    }
    public Set getHoadons() {
        return this.hoadons;
    }
    
    public void setHoadons(Set hoadons) {
        this.hoadons = hoadons;
    }
    public Set getBangluongs() {
        return this.bangluongs;
    }
    
    public void setBangluongs(Set bangluongs) {
        this.bangluongs = bangluongs;
    }
    public Set getBanghes() {
        return this.banghes;
    }
    
    public void setBanghes(Set banghes) {
        this.banghes = banghes;
    }
    public Set getLichcalamviecs() {
        return this.lichcalamviecs;
    }
    
    public void setLichcalamviecs(Set lichcalamviecs) {
        this.lichcalamviecs = lichcalamviecs;
    }




}


