package entities;
// Generated Apr 15, 2016 4:34:07 PM by Hibernate Tools 4.3.1



/**
 * Nhanvientheoca generated by hbm2java
 */
public class Nhanvientheoca  implements java.io.Serializable {


     private String maNvtc;
     private Vitrinhanvien vitrinhanvien;
     private Integer soLuongToiThieu;
     private Integer soLuongToiDa;

    public Nhanvientheoca() {
    }

	
    public Nhanvientheoca(String maNvtc, Vitrinhanvien vitrinhanvien) {
        this.maNvtc = maNvtc;
        this.vitrinhanvien = vitrinhanvien;
    }
    public Nhanvientheoca(String maNvtc, Vitrinhanvien vitrinhanvien, Integer soLuongToiThieu, Integer soLuongToiDa) {
       this.maNvtc = maNvtc;
       this.vitrinhanvien = vitrinhanvien;
       this.soLuongToiThieu = soLuongToiThieu;
       this.soLuongToiDa = soLuongToiDa;
    }
   
    public String getMaNvtc() {
        return this.maNvtc;
    }
    
    public void setMaNvtc(String maNvtc) {
        this.maNvtc = maNvtc;
    }
    public Vitrinhanvien getVitrinhanvien() {
        return this.vitrinhanvien;
    }
    
    public void setVitrinhanvien(Vitrinhanvien vitrinhanvien) {
        this.vitrinhanvien = vitrinhanvien;
    }
    public Integer getSoLuongToiThieu() {
        return this.soLuongToiThieu;
    }
    
    public void setSoLuongToiThieu(Integer soLuongToiThieu) {
        this.soLuongToiThieu = soLuongToiThieu;
    }
    public Integer getSoLuongToiDa() {
        return this.soLuongToiDa;
    }
    
    public void setSoLuongToiDa(Integer soLuongToiDa) {
        this.soLuongToiDa = soLuongToiDa;
    }




}


