package entities;
// Generated Apr 15, 2016 4:34:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Phanquyen generated by hbm2java
 */
public class Phanquyen  implements java.io.Serializable {


     private String maQuyen;
     private String tenGoi;
     private Set vitrinhanviens = new HashSet(0);

    public Phanquyen() {
    }

	
    public Phanquyen(String maQuyen, String tenGoi) {
        this.maQuyen = maQuyen;
        this.tenGoi = tenGoi;
    }
    public Phanquyen(String maQuyen, String tenGoi, Set vitrinhanviens) {
       this.maQuyen = maQuyen;
       this.tenGoi = tenGoi;
       this.vitrinhanviens = vitrinhanviens;
    }
   
    public String getMaQuyen() {
        return this.maQuyen;
    }
    
    public void setMaQuyen(String maQuyen) {
        this.maQuyen = maQuyen;
    }
    public String getTenGoi() {
        return this.tenGoi;
    }
    
    public void setTenGoi(String tenGoi) {
        this.tenGoi = tenGoi;
    }
    public Set getVitrinhanviens() {
        return this.vitrinhanviens;
    }
    
    public void setVitrinhanviens(Set vitrinhanviens) {
        this.vitrinhanviens = vitrinhanviens;
    }




}


