package entities;
// Generated Apr 15, 2016 4:34:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Trangthai generated by hbm2java
 */
public class Trangthai  implements java.io.Serializable {


     private String maTt;
     private String ttbang;
     private String tenTt;
     private Set banghes = new HashSet(0);
     private Set lichcalamviecs = new HashSet(0);
     private Set chitietgoimenus = new HashSet(0);

    public Trangthai() {
    }

	
    public Trangthai(String maTt, String ttbang, String tenTt) {
        this.maTt = maTt;
        this.ttbang = ttbang;
        this.tenTt = tenTt;
    }
    public Trangthai(String maTt, String ttbang, String tenTt, Set banghes, Set lichcalamviecs, Set chitietgoimenus) {
       this.maTt = maTt;
       this.ttbang = ttbang;
       this.tenTt = tenTt;
       this.banghes = banghes;
       this.lichcalamviecs = lichcalamviecs;
       this.chitietgoimenus = chitietgoimenus;
    }
   
    public String getMaTt() {
        return this.maTt;
    }
    
    public void setMaTt(String maTt) {
        this.maTt = maTt;
    }
    public String getTtbang() {
        return this.ttbang;
    }
    
    public void setTtbang(String ttbang) {
        this.ttbang = ttbang;
    }
    public String getTenTt() {
        return this.tenTt;
    }
    
    public void setTenTt(String tenTt) {
        this.tenTt = tenTt;
    }
    public Set getBanghes() {
        return this.banghes;
    }
    
    public void setBanghes(Set banghes) {
        this.banghes = banghes;
    }
    public Set getLichcalamviecs() {
        return this.lichcalamviecs;
    }
    
    public void setLichcalamviecs(Set lichcalamviecs) {
        this.lichcalamviecs = lichcalamviecs;
    }
    public Set getChitietgoimenus() {
        return this.chitietgoimenus;
    }
    
    public void setChitietgoimenus(Set chitietgoimenus) {
        this.chitietgoimenus = chitietgoimenus;
    }




}


