package entities;
// Generated Apr 15, 2016 4:34:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vitrinhanvien generated by hbm2java
 */
public class Vitrinhanvien  implements java.io.Serializable {


     private String maViTri;
     private Phanquyen phanquyen;
     private String tenGoi;
     private Set nhanvientheocas = new HashSet(0);
     private Set nhanviens = new HashSet(0);

    public Vitrinhanvien() {
    }

	
    public Vitrinhanvien(String maViTri, Phanquyen phanquyen, String tenGoi) {
        this.maViTri = maViTri;
        this.phanquyen = phanquyen;
        this.tenGoi = tenGoi;
    }
    public Vitrinhanvien(String maViTri, Phanquyen phanquyen, String tenGoi, Set nhanvientheocas, Set nhanviens) {
       this.maViTri = maViTri;
       this.phanquyen = phanquyen;
       this.tenGoi = tenGoi;
       this.nhanvientheocas = nhanvientheocas;
       this.nhanviens = nhanviens;
    }
   
    public String getMaViTri() {
        return this.maViTri;
    }
    
    public void setMaViTri(String maViTri) {
        this.maViTri = maViTri;
    }
    public Phanquyen getPhanquyen() {
        return this.phanquyen;
    }
    
    public void setPhanquyen(Phanquyen phanquyen) {
        this.phanquyen = phanquyen;
    }
    public String getTenGoi() {
        return this.tenGoi;
    }
    
    public void setTenGoi(String tenGoi) {
        this.tenGoi = tenGoi;
    }
    public Set getNhanvientheocas() {
        return this.nhanvientheocas;
    }
    
    public void setNhanvientheocas(Set nhanvientheocas) {
        this.nhanvientheocas = nhanvientheocas;
    }
    public Set getNhanviens() {
        return this.nhanviens;
    }
    
    public void setNhanviens(Set nhanviens) {
        this.nhanviens = nhanviens;
    }




}


