/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import entities.*;
import dao.*;
import java.util.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author VCAT
 */
public class JFrameThemNhanVienMoi extends javax.swing.JFrame {
    NhanVienDAO nvd = new NhanVienDAO();
    /**
     * Creates new form JFrameThemNhanVienMoi
     */
    public JFrameThemNhanVienMoi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelChucNangDSNV = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtHoTen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtDT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtCMND = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jDCNgaySinh = new com.toedter.calendar.JDateChooser();
        jtxtLuongTheoCa = new javax.swing.JTextField();
        jDCNgayVao = new com.toedter.calendar.JDateChooser();
        jCbbViTri = new javax.swing.JComboBox<>();
        jCbbTDVT = new javax.swing.JComboBox<>();
        jCkbTrangPhuc = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtxtCauHoi = new javax.swing.JTextField();
        jtxtDapAn = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtxtMaNV = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtxtMK = new javax.swing.JTextField();
        jbtnThemNV = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thêm nhân viên mới");

        jPanelChucNangDSNV.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));
        jPanelChucNangDSNV.setToolTipText("");

        jLabel1.setText("Họ tên :");

        jLabel2.setText("Ngày sinh :");

        jLabel3.setText("Điện thoại :");

        jLabel4.setText("CMND :");

        jLabel5.setText("Vị trí :");

        jLabel6.setText("Trình độ vi tính :");

        jLabel7.setText("Ngày vào :");

        jLabel8.setText("Trang phục :");

        jLabel9.setText("Lương theo ca :");

        jCbbViTri.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chủ Nhà Hàng", "Quản Lý Nhà Hàng", "Nhân Viên Thu Ngân", "Nhân Viên Bếp", "Nhân Viên Phục Vụ", "Nhân Viên Pha Chế", "Nhân Viên Tiếp Tân" }));

        jCbbTDVT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Word", "Excel", "Cài Phần Mềm", "Khác" }));

        jCkbTrangPhuc.setText("Đã có");

        jLabel10.setText("Câu hỏi bảo mật :");

        jLabel11.setText("Đáp án :");

        jLabel12.setText("Mã nhân viên :");

        jLabel13.setText("Mật khẩu :");

        javax.swing.GroupLayout jPanelChucNangDSNVLayout = new javax.swing.GroupLayout(jPanelChucNangDSNV);
        jPanelChucNangDSNV.setLayout(jPanelChucNangDSNVLayout);
        jPanelChucNangDSNVLayout.setHorizontalGroup(
            jPanelChucNangDSNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChucNangDSNVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelChucNangDSNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelChucNangDSNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelChucNangDSNVLayout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(9, 9, 9))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelChucNangDSNVLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(7, 7, 7))
                        .addComponent(jLabel1)
                        .addComponent(jLabel7)
                        .addComponent(jLabel5)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12)
                        .addComponent(jLabel13))
                    .addComponent(jLabel8))
                .addGap(23, 23, 23)
                .addGroup(jPanelChucNangDSNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelChucNangDSNVLayout.createSequentialGroup()
                        .addGroup(jPanelChucNangDSNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCbbViTri, javax.swing.GroupLayout.Alignment.TRAILING, 0, 172, Short.MAX_VALUE)
                            .addComponent(jDCNgayVao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtHoTen, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtDT, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDCNgaySinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtMK, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtMaNV)
                            .addComponent(jtxtDapAn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtCauHoi, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCbbTDVT, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtCMND, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtLuongTheoCa, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addComponent(jCkbTrangPhuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelChucNangDSNVLayout.setVerticalGroup(
            jPanelChucNangDSNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChucNangDSNVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelChucNangDSNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelChucNangDSNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanelChucNangDSNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jDCNgayVao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanelChucNangDSNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCbbViTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelChucNangDSNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jDCNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelChucNangDSNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelChucNangDSNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCbbTDVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelChucNangDSNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtLuongTheoCa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelChucNangDSNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtxtCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelChucNangDSNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtxtDapAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelChucNangDSNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jtxtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelChucNangDSNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jtxtMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(jPanelChucNangDSNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jCkbTrangPhuc))
                .addContainerGap())
        );

        jbtnThemNV.setText("Thêm");
        jbtnThemNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnThemNVActionPerformed(evt);
            }
        });

        jButton2.setText("Thoát");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jbtnThemNV)
                .addGap(29, 29, 29)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanelChucNangDSNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelChucNangDSNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnThemNV)
                    .addComponent(jButton2)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbtnThemNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnThemNVActionPerformed
        String  MaNV,MK,CauHoi,DapAn,HoTen,MaViTri="",MaTrDVT="";
        int SDT,CMND,MaVT,MaTDVT,LuongTheoCa;
        boolean TrangPhuc;
        Date NgayBatDau,SN;
        Trinhdovitinh tdvt = new Trinhdovitinh();
        Vitrinhanvien vt = new Vitrinhanvien();
        MaNV = jtxtMaNV.getText().trim();
        MK = jtxtMK.getText().trim();
        CauHoi = jtxtCauHoi.getText();
        DapAn = jtxtDapAn.getText();
        HoTen = jtxtHoTen.getText();
        SDT = Integer.parseInt(jtxtDT.getText());
        CMND = Integer.parseInt(jtxtCMND.getText());
        if(jCkbTrangPhuc.isSelected()){
            TrangPhuc = true;
        }
        MaVT = jCbbViTri.getSelectedIndex();
        MaTDVT = jCbbTDVT.getSelectedIndex();
        switch(MaVT){
            case 0:
                MaViTri = "VT01";
                break;
            case 1:
                MaViTri = "VT02";
                break;
            case 2:
                MaViTri = "VT03";
                break;
            case 3:
                MaViTri = "VT04";
                break;
            case 4:
                MaViTri = "VT05";
                break;
            case 5:
                MaViTri = "VT06";
                break;
            case 6:
                MaViTri = "VT07";
                break;    
        }
    
        switch(MaTDVT){
            case 0:
                MaTrDVT = "TDVT01";
                break;
            case 1:
                MaTrDVT = "TDVT02";
                break;
            case 2:
                MaTrDVT = "TDVT03";
                break;
            case 3:
                MaTrDVT = "TDVT04";
                break;
    }//GEN-LAST:event_jbtnThemNVActionPerformed
        LuongTheoCa = Integer.parseInt(jtxtLuongTheoCa.getText());
        NgayBatDau = jDCNgayVao.getDate();
        SN = jDCNgaySinh.getDate();
        TrangPhuc = jCkbTrangPhuc.isSelected();
        tdvt.setMaTdvt(MaTrDVT);
        vt.setMaViTri(MaViTri);
        Nhanvien nv = new Nhanvien();
        
        nv.setMaNhanVien(MaNV);
        nv.setMatKhau(MK);
        nv.setCauHoiBaoMat(CauHoi);
        nv.setDapAnBaoMat(DapAn);
        nv.setCmnd(CMND);
        nv.setHoTen(HoTen);
        nv.setLuongTheoCa(LuongTheoCa);
        nv.setNgayBatDau(NgayBatDau);
        nv.setNghiViec(false);
        nv.setSinhNhat(SN);
        nv.setSodt(SDT);
        nv.setTrangPhuc(TrangPhuc);
        nv.setTrinhdovitinh(tdvt);
        nv.setVitrinhanvien(vt);
        if(nvd.InsertNV(nv)){
            JOptionPane.showMessageDialog(null, "Thêm nhân viên mới thành công !","Thông báo !",JOptionPane.OK_OPTION);
        }else{
            JOptionPane.showMessageDialog(null, "Thêm nhân viên mới thất bại !","Thông báo !",JOptionPane.OK_OPTION);
        }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameThemNhanVienMoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameThemNhanVienMoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameThemNhanVienMoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameThemNhanVienMoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameThemNhanVienMoi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jCbbTDVT;
    private javax.swing.JComboBox<String> jCbbViTri;
    private javax.swing.JCheckBox jCkbTrangPhuc;
    private com.toedter.calendar.JDateChooser jDCNgaySinh;
    private com.toedter.calendar.JDateChooser jDCNgayVao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelChucNangDSNV;
    private javax.swing.JButton jbtnThemNV;
    private javax.swing.JTextField jtxtCMND;
    private javax.swing.JTextField jtxtCauHoi;
    private javax.swing.JTextField jtxtDT;
    private javax.swing.JTextField jtxtDapAn;
    private javax.swing.JTextField jtxtHoTen;
    private javax.swing.JTextField jtxtLuongTheoCa;
    private javax.swing.JTextField jtxtMK;
    private javax.swing.JTextField jtxtMaNV;
    // End of variables declaration//GEN-END:variables
}
